FROM kalilinux/kali-rolling
LABEL org.opencontainers.image.authors="githubfoam"

RUN apt-get update && apt-get upgrade && apt-get autoremove && apt-get clean

RUN apt-get update && apt-get install -y --no-install-recommends \
    aircrack-ng \
    ncat  \
    hping3

#testing
RUN hping3 -v

WORKDIR /home/ansible