name: "BigBlueButton 2.4 Docker CI workflow"


on:
  push:
    branches: [ test ]


jobs:
  bbb-ubuntu-1804-job:
    name: "bbb  archlinux ubuntu 18.04"
    runs-on: ubuntu-18.04
    # env:
    #   distribution: "archlinux" #https://hub.docker.com/_/archlinux
    #   version: "latest"
    #   name: "archlinux/base"
    #   dockerfilename: "Dockerfile.archlinux"      
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch   
    - name: "BigBlueButton 2.4 Docker"
      run: |
        set -xe
        # https://github.com/bigbluebutton/docker
        git clone -b main --recurse-submodules https://github.com/bigbluebutton/docker.git bbb-docker
        cd bbb-docker
        git submodule update --init
        ls -lai
        sudo ./scripts/setup
        #Start containers 
        # sudo usermod -aG docker `whoami`
        # docker-compose up -d
        # If you use greenlight, you can create an admin account with
        # docker-compose exec greenlight bundle exec rake admin:create
    - name: "Greenlight Docker"
      run: |
        set -xe
        # https://docs.bigbluebutton.org/greenlight/gl-customize.html#customizing-greenlight
        # https://github.com/bigbluebutton/greenlight
        git https://github.com/bigbluebutton/greenlight.git && cd greenlight
        git status
        git remote add upstream https://github.com/bigbluebutton/greenlight.git
        git remote -v
        git fetch upstream
        git checkout -b custom-changes upstream/v2
        git status
        ls -lai
        # cp sample.env .env
        # docker run --rm bigbluebutton/greenlight:v2 bundle exec rake secret
    - name: "Prometheus exporter for BigBlueButton"
      run: |
        set -xe
        # https://github.com/greenstatic/bigbluebutton-exporter
        docker-compose --version
        git clone https://github.com/greenstatic/bigbluebutton-exporter.git
        make docker   
    - name: "Big Blue button monitoring docker"
      run: |
        set -xe
        # https://github.com/ZeitounCorp/bigbluebutton_monitoring
        docker-compose --version
        git clone https://github.com/ZeitounCorp/bigbluebutton_monitoring.git
        cd ~/bigbluebutton_monitoring/bbb-exporter/
        # sudo bbb-conf --secret