name: "bbb CI workflow"


on:
  push:
    branches: [ test ]


jobs:
  bbb-ubuntu-1804-job:
    name: "bbb  archlinux ubuntu 18.04"
    runs-on: ubuntu-18.04
    env:
      distribution: "archlinux" #https://hub.docker.com/_/archlinux
      version: "latest"
      name: "archlinux/base"
      dockerfilename: "Dockerfile.archlinux"      
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch   
    - name: "bbb "
      run: |
        wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | \
          bash -s -- -w -a -v bionic-24 -s bbb.example.com -e info@example.com
