name: "bbb CI workflow"


on:
  push:
    branches: [ test ]


jobs:
  bbb-ubuntu-1804-job:
    name: "bbb  archlinux ubuntu 18.04"
    runs-on: ubuntu-18.04
    env:
      distribution: "archlinux" #https://hub.docker.com/_/archlinux
      version: "latest"
      name: "archlinux/base"
      dockerfilename: "Dockerfile.archlinux"      
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch   
    - name: "Pre-installation checks"
      run: |
        # https://docs.bigbluebutton.org/2.4/install.html#minimum-server-requirements
        #check that the locale of the server is en_US.UTF-8
        cat /etc/default/locale
        sudo apt-get install -y language-pack-en
        sudo update-locale LANG=en_US.UTF-8
        cat /etc/default/locale
        systemctl show-environment
        sudo systemctl set-environment LANG=en_US.UTF-8
        cat /etc/default/locale
        systemctl show-environment
        #check that your server has (at lest) 16G of memory
        free -h
        # check that the server has Ubuntu is 18.04 as its operating system
        cat /etc/lsb-release
        # check that your server is running the 64-bit version of Ubuntu 18.04.
        uname -m
        # check that your server supports IPV6
        # inet6 ::1/128 scope host
        ip addr | grep inet6 
        # check that your server is running Linux kernel 4.x
        uname -r
        # check that your server has (at least) 8 CPU cores
        grep -c ^processor /proc/cpuinfo
    # - name: "bbb "
    #   run: |
    #     wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | \
    #       bash -s -- -w -a -v bionic-24 -s bbb.example.com -e info@example.com
