name: "blackarclinux bash local CI workflow"


on:
  push:
    branches: [ test ]


jobs:

  ubuntu-latest-blackarch-job:
    name: "blackarclinux ubuntu latest"
    runs-on: ubuntu-latest
    env:
      version: "latest"
      name: "archlinux/blackarch"
      dockerfilename: "Dockerfile.archlinux.blackarch"
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch   
    - name: "docker pull archlinux"
      run: sudo docker pull ${distribution}:${version}  && sudo docker image ls  
    - name: "docker build archlinux base"
      run: |
        # destroyed afterwards (use --rm )
        # all subsequent Dockerfile commands generate new images and the cache is not used
        sudo docker build --no-cache --rm  -t ${name}/${version} . --file dockerfiles/${dockerfilename} 
        docker image ls
        docker image history ${name}/${version} 
        docker system df -v               
        docker image inspect ${name}/${version} 