name: "stress load CI workflow"


on:
  push:
    branches: [ test ]


jobs:
  ubuntu-latest-job:
    name: "docker archlinux ubuntu latest"
    runs-on: ubuntu-latest
    env:
      distribution: "archlinux" #https://hub.docker.com/_/archlinux
      version: "latest"
      name: "archlinux/base"
      dockerfilename: "Dockerfile.archlinux"      
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch   
    - name: "docker pull archlinux"
      run: sudo docker pull ${distribution}:${version}  && sudo docker image ls  
    - name: "docker build archlinux base"
      run: |
        # destroyed afterwards (use --rm )
        # all subsequent Dockerfile commands generate new images and the cache is not used
        sudo docker build --no-cache --rm  -t ${name}/${version} . --file dockerfiles/${dockerfilename}
        docker image ls
        docker image history ${name}/${version}
        docker system df -v               
        docker image inspect ${name}/${version}
    - name: "docker build archlinux network security"
      run: |
        # destroyed afterwards (use --rm )
        # all subsequent Dockerfile commands generate new images and the cache is not used
        sudo docker build --no-cache --rm  -t archlinux:netsec . --file dockerfiles/Dockerfile.archlinux.networksecurity 
        docker image ls
        docker image history archlinux:netsec
        docker system df -v               
        docker image inspect archlinux:netsec  